# Generated by Django 4.2.13 on 2026-05-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="car_id",
            field=models.CharField(
                blank=True,
                choices=[("58371", "58371"), ("A07731", "A07731")],
                max_length=20,
                null=True,
            ),
        ),
    ]
