# Generated by Django 4.2.13 on 2026-05-25 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_sale_car_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "Unpaid"),
                    ("partial", "Partial"),
                    ("paid", "Paid"),
                ],
                default="unpaid",
                max_length=10,
            ),
        ),
    ]
